### ISSUE TITLE
Disable completion for hidden commands

### ISSUE THREAD

**Issue by Programie** [stecman/symfony-console-completion#74]
I'm building a command line application with various commands. Some commands are hidden from the command list.

I would expect that my application does not complete commands which are hidden. Currently only the _complete command won't be completed.

**Comment by aik099** [comment]
Completely agree. I don't think that `_complete` command is marked as hidden currently, because it's shown everywhere in docs.

Please send a PR with a change:

1. marking `_complete` command as hidden
2. ignoring hidden commands during auto-complete
3. updated test suite to cover that

For the reference: http://symfony.com/doc/current/console/hide_commands.html
